// examples/vue/src/pages/SimpleForm.vue
<template>
  <div>
    <div style="border: 1px solid #ddd; padding: 24px; border-radius: 8px">
      <FormFactoryComponent
        :schema="schema"
        :components="components"
        :onSubmit="handleSubmit"
        :debug="true"
      />
    </div>

    <div v-if="submittedValues" class="results-panel">
      <h3>Valores Submetidos:</h3>
      <pre>{{ JSON.stringify(submittedValues, null, 2) }}</pre>
      <p class="note">
        💡 Os valores também estão disponíveis no console do navegador (F12)
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { createFormFactory } from '@schepta/factory-vue';
import { components } from '../components/InputComponents';
import simpleFormSchema from '../../../../instances/form/simple-form.json';

const submittedValues = ref<any>(null);

const handleSubmit = (values: any) => {
  console.log('Form submitted:', values);
  submittedValues.value = values;
};

const FormFactoryComponent = createFormFactory({
  schema: simpleFormSchema as any,
  components,
  onSubmit: handleSubmit,
  debug: true,
});
</script>

<style scoped>
.results-panel {
  margin-top: 24px;
  padding: 16px;
  background: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.results-panel h3 {
  margin-top: 0;
}

.results-panel pre {
  background: white;
  padding: 12px;
  border-radius: 4px;
  overflow: auto;
  font-size: 13px;
}

.note {
  margin-top: 12px;
  padding: 8px 12px;
  background: #eff6ff;
  border-left: 3px solid #3b82f6;
  border-radius: 4px;
  font-size: 13px;
  color: #1e40af;
}
</style>

// examples/react/src/basic-ui/components/Forms/SimpleForm.tsx
import { FormFactory } from "@schepta/factory-react";
import { components } from "../../ComponentRegistry";
import { useState } from "react";
import React from "react";
import { FormSchema } from "@schepta/core";
import simpleFormSchema from "../../../../../../instances/form/simple-form.json";

export const SimpleForm = () => {
  const schema = simpleFormSchema as FormSchema;
  const [submittedValues, setSubmittedValues] = useState<any>(null);

  const handleSubmit = (values: any) => {
    console.log("Form submitted:", values);
    setSubmittedValues(values);
  };

  return (
    <>
      <div
        style={{
          border: "1px solid #ddd",
          padding: "24px",
          borderRadius: "8px",
        }}
      >
        <FormFactory
          schema={schema}
          components={components}
          onSubmit={handleSubmit}
          debug={true}
        />
      </div>

      {submittedValues && (
        <div
          style={{
            marginTop: "24px",
            padding: "16px",
            background: "#f9fafb",
            border: "1px solid #e5e7eb",
            borderRadius: "8px",
          }}
        >
          <h3 style={{ marginTop: 0 }}>Valores Submetidos:</h3>
          <pre
            style={{
              background: "white",
              padding: "12px",
              borderRadius: "4px",
              overflow: "auto",
              fontSize: "13px",
            }}
          >
            {JSON.stringify(submittedValues, null, 2)}
          </pre>
          <p
            style={{
              marginTop: "12px",
              padding: "8px 12px",
              background: "#eff6ff",
              borderLeft: "3px solid #3b82f6",
              borderRadius: "4px",
              fontSize: "13px",
              color: "#1e40af",
            }}
          >
            💡 Os valores também estão disponíveis no console do navegador (F12)
          </p>
        </div>
      )}
    </>
  );
};
