// examples/vue-vuetify/src/pages/SimpleForm.vue
<template>
  <div>
    <v-card elevation="2" class="pa-4">
      <FormFactoryComponent />
    </v-card>

    <v-card v-if="submittedValues" elevation="2" class="pa-4 mt-4">
      <h3 class="mb-3">Valores Submetidos:</h3>
      <v-card variant="outlined" class="pa-3">
        <pre style="margin: 0; font-size: 13px; overflow: auto;">{{ JSON.stringify(submittedValues, null, 2) }}</pre>
      </v-card>
      <v-alert type="info" variant="tonal" class="mt-3" density="compact">
        💡 Os valores também estão disponíveis no console do navegador (F12)
      </v-alert>
    </v-card>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { createFormFactory } from '@schepta/factory-vue';
import { components } from '../components/InputComponents';
import simpleFormSchema from '../../../../instances/form/simple-form.json';

const submittedValues = ref<any>(null);

const handleSubmit = (values: any) => {
  console.log('Form submitted:', values);
  submittedValues.value = values;
};

const FormFactoryComponent = createFormFactory({
  schema: simpleFormSchema as any,
  components,
  onSubmit: handleSubmit,
  debug: true,
});
</script>

// examples/react/src/basic-ui/components/Forms/SimpleForm.tsx
import { FormFactory } from "@schepta/factory-react";
import { components } from "../../ComponentRegistry";
import { useState } from "react";
import React from "react";
import { FormSchema } from "@schepta/core";
import simpleFormSchema from "../../../../../../instances/form/simple-form.json";

export const SimpleForm = () => {
  const schema = simpleFormSchema as FormSchema;
  const [submittedValues, setSubmittedValues] = useState<any>(null);

  const handleSubmit = (values: any) => {
    console.log("Form submitted:", values);
    setSubmittedValues(values);
  };

  return (
    <>
      <div
        style={{
          border: "1px solid #ddd",
          padding: "24px",
          borderRadius: "8px",
        }}
      >
        <FormFactory
          schema={schema}
          components={components}
          onSubmit={handleSubmit}
          debug={true}
        />
      </div>

      {submittedValues && (
        <div
          style={{
            marginTop: "24px",
            padding: "16px",
            background: "#f9fafb",
            border: "1px solid #e5e7eb",
            borderRadius: "8px",
          }}
        >
          <h3 style={{ marginTop: 0 }}>Valores Submetidos:</h3>
          <pre
            style={{
              background: "white",
              padding: "12px",
              borderRadius: "4px",
              overflow: "auto",
              fontSize: "13px",
            }}
          >
            {JSON.stringify(submittedValues, null, 2)}
          </pre>
          <p
            style={{
              marginTop: "12px",
              padding: "8px 12px",
              background: "#eff6ff",
              borderLeft: "3px solid #3b82f6",
              borderRadius: "4px",
              fontSize: "13px",
              color: "#1e40af",
            }}
          >
            💡 Os valores também estão disponíveis no console do navegador (F12)
          </p>
        </div>
      )}
    </>
  );
};
