// showcases/src/frameworks/vue/vuetify/components/Form.vue
<template>
  <div>
    <FormFactory
      :schema="schema"
      :components="customComponents"
      @submit="handleSubmit"
    />

    <div v-if="submittedValues" style="margin-top: 2rem; padding: 1rem; background: #e3f2fd; border-radius: 4px;">
      <h3 style="margin-bottom: 0.5rem; color: #1976d2;">Submitted Values:</h3>
      <pre style="background: white; padding: 1rem; border-radius: 4px; overflow: auto;">{{ JSON.stringify(submittedValues, null, 2) }}</pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { FormFactory } from '@schepta/factory-vue';
import { components as customComponents } from './ComponentRegistry';
import type { FormSchema } from '@schepta/core';

defineProps<{
  schema: FormSchema;
}>();

const submittedValues = ref<Record<string, any> | null>(null);

const handleSubmit = (values: Record<string, any>) => {
  console.log('Form submitted:', values);
  submittedValues.value = values;
};
</script>

// examples/react/src/basic-ui/components/Form.tsx
import React, { useState } from "react";
import { FormFactory } from "@schepta/factory-react";
import { FormSchema } from "@schepta/core";

interface FormProps {
  schema: FormSchema;
  onSubmit?: (values: Record<string, any>) => void;
}

export const Form = ({ schema, onSubmit }: FormProps) => {
  const [submittedValues, setSubmittedValues] = useState<Record<string, any> | null>(null);

  const handleSubmit = (values: Record<string, any>) => {
    console.log('Form submitted:', values);
    setSubmittedValues(values);
    onSubmit?.(values);
  };

  return (
    <>
      <div
        style={{
          border: "1px solid #ddd",
          padding: "24px",
          borderRadius: "8px",
        }}
      >
        <FormFactory
          schema={schema}
          onSubmit={handleSubmit}
          debug={true}
        />
      </div>
      {submittedValues && (
        <div style={{
          marginTop: '24px',
          padding: '16px',
          background: '#f9fafb',
          border: '1px solid #e5e7eb',
          borderRadius: '8px',
        }}>
          <h3 style={{ marginTop: 0 }}>Submitted Values:</h3>
          <pre style={{
            background: 'white',
            padding: '12px',
            borderRadius: '4px',
            overflow: 'auto',
            fontSize: '13px',
          }}>
            {JSON.stringify(submittedValues, null, 2)}
          </pre>
        </div>
      )}
    </>
  );
};
