// showcases/src/frameworks/vue/vuetify/components/Form.vue
<template>
  <div>
    <FormFactory
      :schema="schema"
      :components="customComponents"
      @submit="handleSubmit"
    />

    <div v-if="submittedValues" style="margin-top: 2rem; padding: 1rem; background: #e3f2fd; border-radius: 4px;">
      <h3 style="margin-bottom: 0.5rem; color: #1976d2;">Submitted Values:</h3>
      <pre style="background: white; padding: 1rem; border-radius: 4px; overflow: auto;">{{ JSON.stringify(submittedValues, null, 2) }}</pre>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { FormFactory } from '@schepta/factory-vue';
import { components as customComponents } from './ComponentRegistry';
import type { FormSchema } from '@schepta/core';

defineProps<{
  schema: FormSchema;
}>();

const submittedValues = ref<Record<string, any> | null>(null);

const handleSubmit = (values: Record<string, any>) => {
  console.log('Form submitted:', values);
  submittedValues.value = values;
};
</script>

// examples/react/src/material-ui/components/Form.tsx
import React, { useState } from "react";
import { Paper, Box, Typography } from "@mui/material";
import { FormSchema } from "@schepta/core";
import { FormFactory } from "@schepta/factory-react";
import { components } from "./ComponentRegistry";

interface FormProps {
  schema: FormSchema;
  onSubmit?: (values: Record<string, any>) => void;
}

export const Form = ({ schema, onSubmit }: FormProps) => {
  const [submittedValues, setSubmittedValues] = useState<Record<string, any> | null>(null);

  const handleSubmit = (values: Record<string, any>) => {
    console.log('Form submitted:', values);
    setSubmittedValues(values);
    onSubmit?.(values);
  };

  return (
    <>
      <Paper
        elevation={2}
        sx={{ p: 4 }}
      >
        <FormFactory
          schema={schema}
          components={components}
          onSubmit={handleSubmit}
          debug={true}
        />
      </Paper>
      {submittedValues && (
        <Paper elevation={1} sx={{ mt: 3, p: 2, bgcolor: 'grey.50' }}>
          <Typography variant="subtitle1" gutterBottom>
            Submitted Values:
          </Typography>
          <Box
            component="pre"
            sx={{
              bgcolor: 'white',
              p: 2,
              borderRadius: 1,
              overflow: 'auto',
              fontSize: '13px',
            }}
          >
            {JSON.stringify(submittedValues, null, 2)}
          </Box>
        </Paper>
      )}
    </>
  );
};
